@Api_HostAddress = http://localhost:5157

GET {{Api_HostAddress}}/Currency/latest?currency=usd
Accept: application/json

###

GET {{Api_HostAddress}}/Currency/convert?currency=usd&amount=128
Accept: application/json

###

GET {{Api_HostAddress}}/Currency/history?currency=usd&fromDate=2024-4-10&toDate=2024-5-17&page=1&size=50
Accept: application/json

###